---
- hosts: all
  gather_facts: yes
  connection: local

  tasks:
  - name: return motd to registered var
    command: cat /home/po/all_abot_awx/test_pro_ansible/test_file
    register: mymotdg

  - name: debug someting
    debug:
      var: "{{ mymotdg }}"

  - name: now to got hell
